### ISSUE TITLE
Optionally following symlinks

### ISSUE THREAD

**Issue by stuhood** [notify-rs/notify#255]
Hey folks! Have been happily using `5.0.0.pre2` for a few months now.

Our use of the `notify` crate is symlink aware, so before running `read_link`, we ensure that we use this crate's API to watch it. The behavior of `read_link` is to return the destination of a symlink, _even if it is dead_, and we rely on that in order to track the existence of the symlink and watch it in case it changes.

But on linux, the `notify` crate's `inotify` implementation currently doesn't set [IN_DONT_FOLLOW](https://linux.die.net/man/7/inotify):
```
    IN_DONT_FOLLOW (since Linux 2.6.15) 

Don't dereference pathname if it is a symbolic link. 
```
... which means that the attempt to watch a dead symlink fails.

----

To work around this, I have a [small patch](https://github.com/notify-rs/notify/commit/64880f0662db2b5ecbf25f1cccdca64bb8fac1bc) to the crate that currently just... unconditionally sets `IN_DONT_FOLLOW` (which is clearly not landable as is), and then another landable patch to avoid stating things unnecessarily: #256.  But I'd like to help ensure that this can be supported upstream, and would be interested in suggestions for how it could be included into the API as an optional toggle.

A global toggle per-watcher would be sufficient for our usecase, but it's also possible that some callers would prefer this on a watch-by-watch basis. Alternatively, perhaps a `Watcher::symlink_watch` method that was the spiritual equivalent of https://doc.rust-lang.org/std/path/struct.Path.html#method.symlink_metadata... ie, not reading/watching through a symlink if it existed?

**Comment by 0xpr03** [comment]
Coming back to this: I think we want some toggle at first and land some defense against dead symlinks. In light of #291 I think we should rather use ignore-sets to let people "disable" symlinks per-path. Everything else is probably too much overhead and possibly confusing.

**Comment by stuhood** [comment]
> Coming back to this: I think we want some toggle at first and land some defense against dead symlinks. In light of #291 I think we should rather use ignore-sets to let people "disable" symlinks per-path. Everything else is probably too much overhead and possibly confusing.

#291 seems like it would primarily affect the recursive watch API: with regard to watching individual/single paths, having per-path flexibility would be preferable I think.

I suspect that given how different their settings and behavior are, that rather than a single `watch` function with a `RecursiveMode` enum, there should be two functions. Maybe something like:
```
fn watch_single<P: ..>(&mut self, path: P, options: SingleWatchOptions) -> ..;
fn watch_recursive<P: ..>(&mut self, path: P, options: RecursiveWatchOptions) -> ..;
```
(...which is on some level akin to 1) adding more options/settings to `RecursiveMode` and 2) renaming it.)

**Comment by tdyas** [comment]
I am one of the maintainers of the https://github.com/pantsbuild/pants repository.  This issue was originally reported by @stuhood who is also a maintainer of that project. I'd like to help resolve this issue so we can stop using an out-of-date, forked copy of `notify` in that project.

Are there any thoughts on an appropriate API for disabling following symlinks?

**Comment by vpzomtrrfrt** [comment]
Was this issue resolved by #635?

**Comment by benjyw** [comment]
Hi, another maintainer of https://github.com/pantsbuild/pants here.  #635 doesn't resolve this issue, alas. That PR relates to directory traversal, not watch semantics.

As implemented, `follow_links` in #635 only impacts whether symlinks to directories are traversed through in a recursive watch. For symlinks to files, regardless of `follow_links`, the `DirEntry`s obtained from WalkDir have `path` set to the link name, and that is what is passed to `add_single_watch()`. So for files we're (always!) passing the symlink src down to inotify instead of the dst. So far so good! But inotify itself will dereference the symlink and watch the destination, unless IN_DONT_FOLLOW is set. 

So, arguably, if `follow_links=false` then this crate should also set `IN_DONT_FOLLOW`? As it stands, if `follow_links=false` then the end user will perceive that symlinks appear to be followed. In particular, for symlinks to directories, with `follow_links=false`, inotify will watch the entire directory...

If maintainers of this crate agree I am happy to whip up a PR.

cc @tdyas @stuhood

**Comment by benjyw** [comment]
That said, I will have to test if we are relying on following *directory* symlinks. If we are then the solution above won't work for our use case.

**Comment by dfaust** [comment]
> If maintainers of this crate agree I am happy to whip up a PR.

Sounds good.

Although I don't get this part: "In particular, for symlinks to directories, with follow_links=false, inotify will watch the entire directory...". As far as I see, the issue should only be with symlinked files. What am I missing?

I'm wondering if we can write a test for this (similar to https://github.com/notify-rs/notify/blob/a072ed88670ea0a6c1fb99ddf240da40c588185d/notify/src/lib.rs#L421). At some point we removed our old tests because they were too flaky. But this new approach seems to be very stable.

**Comment by benjyw** [comment]
> > If maintainers of this crate agree I am happy to whip up a PR.
> 
> Sounds good.
> 
> Although I don't get this part: "In particular, for symlinks to directories, with follow_links=false, inotify will watch the entire directory...". As far as I see, the issue should only be with symlinked files. What am I missing?
> 

Well, this is just from my eyeballing the code, I would need to confirm with a test, but as far as I can tell, if `follow_links==false` (or, for that matter, if `is_recursive==false`) then we call `self.add_single_watch(...)` on the path of the symlink source. inotify will dereference the symlink, see that it's a directory, and watch it, which will cause it to also (non-recursively) watch all the files in that directory, which might be unexpected to the user who requested `follow_links=false`?

**Comment by tobni** [comment]
I took a stab at designing a fix for this that pants can use here https://github.com/notify-rs/notify/pull/967.

inotify supports this via `IN_DONT_FOLLOW`, there is just no way to ask for it. On Config it would apply to every watch, so I put it on the path:

```rust
watcher.watch_with(
    Path::new("link"),
    WatchPathConfig::new(RecursiveMode::NonRecursive)
        .with_dereference_symlinks(false),
)?;
```
@dfaust PTAL
